### ISSUE TITLE
Mac系统 Python3.7 提示ImportError: cannot import name '__version__' from 'smsBomb'  请问这是为什么 ？

### ISSUE THREAD

**Issue by imlinchun** [shellvon/smsBomb#13]
ImportError: cannot import name '__version__' from 'smsBomb'

**Comment by arnoldxiao** [comment]
直接`import smsBomb`代替

**Comment by xiaoyagao** [comment]
直接用import smsBomb也不行的。

**Comment by xiaoyagao** [comment]
替换之后又会显示  No module named smsbomb

**Comment by Coco-wxf** [comment]
我的也是这种情况，ImportError: cannot import name '__version__' from partially initialized module 'smsBomb' (most likely due to a circular import)
