### ISSUE TITLE
ImportError: cannot import name '__version__' from 'smsBomb'

### ISSUE THREAD

**Issue by zhsrain** [shellvon/smsBomb#4]
win10 python3.7
ImportError: cannot import name '__version__' from 'smsBomb'
how can i run it?

**Comment by shellvon** [comment]
just type `python -m smsBobm -h` in the project dir.

**Comment by shellvon** [comment]
@zhsrain I'm closing this issue because it has been inactive for a few days. Please re-open if you still need help with this issue.

**Comment by shellvon** [comment]
same with #7
