### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by nanba-dengtao** [shellvon/smsBomb#5]
无法用python命令正常运行，请您看看

![jietu](https://user-images.githubusercontent.com/37473449/43715649-b9e9ec88-99b3-11e8-96ad-81f9d3748200.png)

**Comment by shellvon** [comment]
看你的截图是没有安装 `coloredlogs` 依赖。

Python的依赖包一般都写在 `requirments.txt` 里面，你需要在跑之前执行 `pip install -r requirments.txt`。 如果是 GUI 则执行的是 `pip install -r requirments-gui.txt`。
