### ISSUE TITLE
运行后出现ImportError

### ISSUE THREAD

**Issue by zhaiziweilove** [shellvon/smsBomb#7]
请教运行之后出现以下错误怎么解决？网上搜了没找到方案。
ImportError: cannot import name '__version__' from 'smsBomb'
输入`python -m smsBobm -h`也是弹出这个错误

**Comment by shellvon** [comment]
烦请给一下 Python版本 & 运行环境 & 复现命令。

**Comment by zhaiziweilove** [comment]
Python 版本：3.7.0
操作系统：Window 10 专业版 1803 17134.345
[https://i.loli.net/2018/10/25/5bd163ac4b53b.jpg](url)

**Comment by shellvon** [comment]
我这边暂时没有Windows 和 Python3.7 因此可能会晚一点回复你。

**Comment by shellvon** [comment]
不好意思，如此晚才回复。
我测试了2台 Windows 10 + Python 3.7 暂时没发现此问题，您能否提供一下您安装 Python 的方式，我将按照您给定的方式再试试。

**Comment by zhaiziweilove** [comment]
Python 是用Chocolatey安装的，不知道是否有影响

**Comment by shellvon** [comment]
@zhaiziweilove 也许与这个有关系，你尝试一下把 [smsBomb/smsBomb.py](https://github.com/shellvon/smsBomb/blob/master/smsBomb/smsBomb.py) 中与 `__version__` 相关的地方都删除试试呢。反正它实际上并不会影响什么功能，一共两处:

https://github.com/shellvon/smsBomb/blob/35f82e6fdf943e8af4fe649d710efd73daef26b8/smsBomb/smsBomb.py#L16
https://github.com/shellvon/smsBomb/blob/35f82e6fdf943e8af4fe649d710efd73daef26b8/smsBomb/smsBomb.py#L83

**Comment by shellvon** [comment]
我不是很清楚是否和安装的python方式有关系，建议你们换一下安装方式试试。

shellvon

**Comment by willshion** [comment]
我也是 version问题
win10 x64 Python3.6

**Comment by arnoldxiao** [comment]
直接`import smsBomb`代替

**Comment by zhaiziweilove** [comment]
@arnoldxiao 按照您这样改了之后打开直接结束，似乎无解。

**Comment by arnoldxiao** [comment]
> @arnoldxiao 按照您这样改了之后打开直接结束，似乎无解。

我也是，不会报错，但是似乎也没有收到短信

**Comment by shellvon** [comment]
@arnoldxiao @zhaiziweilove 
这个项目里面用到的配置基本已经失效了，所以攻击会失败，自然也就收不到短信。另外，目前的短信渠道商大多数都添加了IP白名单限制，所以即使有账号可能也会失败。

如果依然选择本产品攻击，我建议把配置改成 normal 然后抓一下一些小网站不需要签名的发送短信的接口即可，比如这里:

https://github.com/Girler/SMSBombing/blob/b46033aae5dbf36cab88f6e54dc7be5be182b501/api.php#L53-L576

这里面的网站都可以使用本项目产品`normal`进行攻击。

**Comment by zhaiziweilove** [comment]
主要是连打开都打开不了，只能看看源代码向大佬学习一下TAT
